mtuaturl=http://205.147.100.121/WealthWeb/ws/login/release
mtuatusername=sat001
mtuatpassword=password1

52url=https://caliber.rupeex.com/cas/login?service=https%3A%2F%2Fcaliber.rupeex.com%2FWealthWeb%2Fws%2Fsecure%2FsecureGate%2Fhome
52username=admin
52password=rupeelog
52role=Admin

democaliberurl=http://demo.fincaliber.com/WealthWeb/ws/login/ulogin
democaliberusername=admin
democaliberpassword=rupeelog
democaliberrole=Admin
