############################################################################################################
#						 ACCOUNTING
############################################################################################################

############################################################################################################
#						 Voucher_upload
############################################################################################################

filepath=./WealthWeb/DataFiles/Voucher_upload_template.xlsx

############################################################################################################
#						 ACCOUNTING 
############################################################################################################
#   MTUAT                    Corpus In-Cash Create
clientAccountPortfolioAutoSuggSearch=sachin
selectClientAccountPortfolio=IA149499_JJSPL4785K_Automation Testing_Automation Testing_IA149499D15_Sachin
sourceBankDD=ICICI Bank Ltd ( 77171717171)
amount=100
targetBankDD= ICICI Bank Ltd ( 771717188191 )
instrumentType=Cheque
referenceNo=1023
instrumentDated=26/02/2021
narrationRemarks=Entered valid data

############################################################################################################
# Demo fincaliber
############################################################################################################
#clientAccountPortfolioAutoSuggSearch=ram
#selectClientAccountPortfolio=IA739_CDEFA1228L_Balaram_Balaram_IA739E638_Balaram
#sourceBankDD=Abhyudaya Coop Bank ( 300339) 
#amount=5000
#targetBankDD= Abhyudaya Coop Bank ( 300339 )
#instrumentType=NEFT
#referenceNo=4022
#instrumentDated=07/10/2020
#narrationRemarks=Entered valid data
############################################################################################################
#                       Corpus Out-Cash Create
############################################################################################################
outCashclientAccountPortfolioAutoSuggSearch=sachin
outCashselectClientAccountPortfolio=IA149499_JJSPL4785K_Automation Testing_Automation Testing_IA149499D15_Sachin
outCashsourceBankDD= ICICI Bank Ltd ( 771717188191 )
outCashamount=10
outCashtargetBankDD=ICICI Bank Ltd ( 77171717171)
outCashinstrumentType=Cheque
outCashreferenceNo=01
outCashinstrumentDated=26/02/2021
outCashnarrationRemarks=Entered valid data


#Home/Accounting/Corpus Stock In-Out
#CreateCorpusStockInReceiptEQTC
cInSEQClientAcPortfAutoSugg=ram chennale
selectcInSEQClientAcPortfAutoSugg=IA149552_RCBPL1027R_Ram Raj chennale5_Ram chennale5_IA149552E149561
cInSEQTargetDematDD= 12345501
cInSEQSourceDemat= 12345101
cInSEQScripNameAutoSugg=muthoot
selectcInSEQScripNameAutoSugg=Muthoot Capital Services Limited_BSE(511766)_NSE(MUTHOOTCAP)
cInSEQQuantity=10
cInSEQReceiptDate=03/03/2021
cInSEQRate=100



#Home/Accounting/Corpus Stock In-Out
#CreateCorpusStockInDebtTC
cInSDebtClientAcPortfAutoSugg=ram chennale
selectcInSDebtClientAcPortfAutoSugg=IA149552_RCBPL1027R_Ram Raj chennale5_Ram chennale5_IA149552E149561
cInSDebtTargetDematDD= 12345501
cInSDebtSourceDematDD= 12345101
cInSDebtIssuerDD= A. K. CAPITAL FINANCE PRIVATE LIMITED
cInSDebtInstruDD= A. K. CAPITAL FINANCE PRIVATE LIMITED SR-A-I 9.6 LOA 07MR22 FVRS1LAC(INE197P07011)
cInSDebtQuantity=10
cInSDebtReceiptDate=03/03/2021
cInSDebtPrice=100

#Home/Accounting/Corpus Stock In-Out
#CreateCorpusStockInManagedAccTC
cInSMAClientAcPortfAutoSugg=ram chennale
selectcInSMAClientAcPortfAutoSugg=IA149552_RCBPL1027R_Ram Raj chennale5_Ram chennale5_IA149552E149561
cInSMAReceiptDate=03/03/2021
cInSMAadvisorDD= sathya IFA
cInSMASchemeDD= Caliber amc 1(CALAMC)
cInSMAamount=100


cOutSEQClientAccPortfAutoSugg=ram chennale
selectcOutSEQClientAccPortfAutoSugg=IA149552_RCBPL1027R_Ram Raj chennale5_Ram chennale5_IA149552E149561
cOutSEQSourceDemat= 12345501
cOutSEQTargetDematDD= 12345101
cOutSEQWithdrawalDate=04/03/2021
cOutSEQWithdrawalRateDD=Holding Cost
cOutSEQWithdrawalQuantity=1


#Home/Accounting/Corpus Stock In-Out
#CreateCorpusStockOutDebtTC
cOutSDebtClientAccPortfAutoSugg=ram chennale
selectcOutSDebtClientAccPortfAutoSugg=IA149552_RCBPL1027R_Ram Raj chennale5_Ram chennale5_IA149552E149561
cOutSDebtSourceDemat= 12345501
cOutSDebtTargetDematDD= 12345101
cOutSDebtWithdrawalDate=05/03/2021
cOutSDebtWithdrawalRateDD=Holding Cost
cOutSDebtWithdrawalQuantity=1


#Home/Accounting/Corpus Stock In-Out
#CreateCorpusStockOutManagedAccTC
cOutSMAClientAccPortfAutoSugg=ram chennale
selectcOutSMAClientAccPortfAutoSugg=IA149552_RCBPL1027R_Ram Raj chennale5_Ram chennale5_IA149552E149561
cOutSMAstockOutDate=05/03/2021
cOutSMAmaAdvisorDD= sathya IFA
cOutSMAmaSchemeDD= Caliber amc 1(CALAMC)
cOutSMAcorpOutAmt=10
cOutSMAdate=05/03/2021

#Home/Accounting/Corpus Stock In-Out
#ViewCorpusStockInOutTC
accountingPortfAutoSugg=ram chennale
selectaccountingPortfAutoSugg=IA149552_RCBPL1027R_Ram Raj chennale5_Ram chennale5_IA149552E149561

#Home/Accounting/Manual Voucher
#CreateJournalVoucherTC
jvPortfolioAutoSugg=ram chennale
selectjvPortfolioAutoSugg=IA149552_RCBPL1027R_Ram Raj chennale5_Ram chennale5_IA149552E149561
jvVoucherDate=
jvAccGroupsDD_1=
jvLedgerNameDD_1=
jvDebitAmount_1=100
jvCreditAmount_1=100
jvNarration_1=10


#Home/Accounting/Manual Voucher
#CreatePaymentVoucherTC
pvVoucherDate=09/03/2021
pvPortfolioAutoSugg=ram chennale
selectpvPortfolioAutoSugg=IA149552E149561_RCBPL1027R_Ram Raj chennale5_Ram chennale5
pvBankDD= 12345678901002
pvAccTypeDD= Advanced Interest Due (Debt)
pvSecLedDD= Advanced Interest Due (Debt)
pvAmount=10
pvInstrumentTypeDD=Cheque
pvInstRefNo=23
pvInstDate=09/03/2021
pvPaymentInFavour=Rupeelog
pvNarration=Wrt NBFC

#Home/Accounting/Manual Voucher
#CreateReceiptVoucherTC
rvVoucherDate=09/03/2021
rvPortfolioAutoSugg=ram chennale
selectrvPortfolioAutoSugg=IA149552E149561_RCBPL1027R_Ram Raj chennale5_Ram chennale5
rvBankDD= 12345678901002
rvAccTypeDD= Advanced Interest Due (Debt)
rvSecLedDD= Advanced Interest Due (Debt)
rvAmount=10
rvInstrumentTypeDD=Cheque
rvInstRefNo=23
rvInstDate=09/03/2021
rvNarration=Wrt NBFC


#Home/Accounting/Manual Voucher
#CreateContraVoucherTC
cvVoucherDate=09/03/2021
cvPortfolioAutoSugg=ram chennale
selectcvPortfolioAutoSugg=IA149552E149561_RCBPL1027R_Ram Raj chennale5_Ram chennale5
cvSrcBankDD= 12345678901002
cvTargetBankDD=
cvAmount=10
cvInstrumentTypeDD=Cheque
cvInstRefNo=23
cvInstDate=09/03/2021
cvNarration=Wrt NBFC


#Home/Accounting/Manual Voucher
#ViewManualVoucherTC
mvAccountingPortfAutoSugg=ram chennale
mvSelectaccountingPortfAutoSugg=IA149552E149561_RCBPL1027R_Ram Raj chennale5_Ram chennale5



