#################################################################################################
                      #RerunEquitySplitBonus#
#################################################################################################
# Run Split Bonus Process For a Particular Client 
clientPortfolioNameAutoSuggSearch=sachin
selectParticularClientPortfolio=SACHIN NANDKUMAR RAKHADE_AABPR4129A_IA149310E149292
Clientdate=01/10/2020
#################################################################################################

#Run Split Bonus Process For a Particular Asset
assetEquityAutoSuggSearch=icici
selectParticularAsset=ICICI Lombard General Insurance Company Ltd_BSE(540716)_NSE(ICICIGI)
assetDate=01/10/2020
#################################################################################################














































































