############################################################################################################
							# Client Bank Mapping #
############################################################################################################
clientBankMappingSearchClientName=all txn
clientBankMappingSelectClient=IA149389_QQAMA7845P_all txn_all txn
ClientBankIFSCcodeAutoSuggSearch=ICIC0000002
selectIFSCcode=ICIC0000002
bankAccountTypeDD=Current
bankAccountNo=43212141391
isDefaultForWealthDD=Yes
isMtfDD=Yes
isDefaultForMTFDD=Yes
isItPOADD=Yes
holderName1=jay
holderName1=jayraj
holderName1=jayram

############################################################################################################
							# Client Demat Mapping #
############################################################################################################
deClientnameAutoSuggSearch=test
dematSelectClient=IA149524_EOXPH9076M_Test Fortune_Test Fortune
depositoryParticipantDD=12010600(ANAND RATHI SHARE AND STOCK BROKERS LIMITED)
clientDPAccNo=12125119185
isDefaultForDematDD=Yes
isMTFDD=Yes
isDefaultForMTFDD=Yes
statusDD=Active
POADD=Yes
custodyCode1=011
custodyCode2=012
custodyCode3=013
custodyCode4=014
custodyCode5=015
holderName1=Ram
holderName2=Raj
holderName3=Ramu

############################################################################################
#Add Family AddFamilyPage class
############################################################################################
familyName=Ram chennale7 Family
globalFamilyCode=20312
selectKyph1AutoSuggSearch=ram
Kyph1AutoSuggSearch=ACEPL7142C - Vikram Mukund Limaye - 1000007757
selectKyph2AutoSuggSearch=JJSPL4785K - Automation Testing - UCIC153732
Kyph2AutoSuggSearch=JJSPL4785K - Automation Testing - UCIC153732
selectKyph3AutoSuggSearch=JJSPL4785K - Automation Testing - UCIC153732
Kyph3AutoSuggSearch=JJSPL4785K - Automation Testing - UCIC153732
reportFrequencyDropDown=Annual
statusDropDown=Active
fpKyphAutoSuggSearch=JJSPL4785K - Automation Testing - UCIC153732
KyphAutoSuggSearch=JJSPL4785K - Automation Testing - UCIC153732

############################################################################################
#Add new Individual Kyph == SAME INPUT DATA == Create KyphFCP
############################################################################################
#KYC
kycNum=5027
panNo=AKGPC5010N
kycStatus=Yes
kycStatusDate=06/10/2020
kycDownlDate=06/10/2020
name=JohnJ10
mname=kritina10
lname=Anthony10
exCate=Court Receiver
maidN=kristina
maidMN=kristina
maidLN=kristina
motherN=Rajini
motherM=Jonrak
motherL=Kelram
fsName=Ragir
relKyph=Father
gender=Male
#maritalStatus=Married
dob=29/08/1984
nationality=Indian
legalStatus=Body Corporate
residentSt=Bank / Financial Institution_New
#adhar=547687209641
#vidNo=3432424234234324
#accType=Normal
corrAdr=HSR Layout Bengalore
adrType1=Business
corrAdrType=India
kycPincode=585328
org=Sathya IFA-1
#officeTel=563464
#resTel=874748
#reKyc=Yes
#mobile=8833893987
#fax=5342
period=12 Months
email=ram.c@rupeelog.com
permAdr=Bhalki Bidar KA
adrType2=Business
permAdrType=India
permPincode=585328
anyInf=contact us when required

#KyphFCP
createFCPDD=Yes
organisationDDSL=Sathya IFA-1


#FATCA

gPanNo=AKGPC5011N
gname=Ramesh
grel=Brother
adrType=Business
birthPlace=bhalki
birthCtry=INDIA
appIncomVl=>10 <= 25 Lacs
occup=Service
sourceOfIncome=Ancestral Property
totNetWorth=2
netWorthAsOn=06/10/2020
pep=Not Applicable
anyotherInfo=valid data
cTxRes1=INDIA
taxID1=AKGPC8277N
idType1=PAN card
cTxRes2=INDIA
taxID2=AKGPC1177N
idType2=PAN card
cTxRes3=INDIA
taxID3=AKGPC9277N
idType3=PAN card
cTxRes4=INDIA
taxID4=6577
idType4=Company Identification Number  issueOccured

#Specific

salutation=Mr
riskProfInvetPlcy=High Risk
riskProfPMLAPlcy=High Risk
doeCltHavAsset=Yes
clientOrg=Rupeelog

# KRA Status

cdsl=On Hold
nsdl=On Hold
dotex=On Hold
cams=On Hold
karvya=On Hold
annivDate=06/10/2020
dobSpouse=06/10/2000
defAdr=Permanent Address
dateCommen=06/10/2020
uid=123454326551

#################################################################################################
                      ##Create KyphFCP##
#################################################################################################
#KYC
fkycNum=50211
fpanNo=AKGPC5014N
fkycStatus=Yes
fkycStatusDate=06/10/2020
fkycDownlDate=06/10/2020
fname=John6
fmname=kritina6
flname=Anthony6
fexCate=Court Receiver
fmaidN=kristina
fmaidMN=kristina
fmaidLN=kristina
fmotherN=Rajini
fmotherM=Jonrak
fmotherL=Kelram
ffsName=Ragir
frelKyph=Father
fgender=Male
#fmaritalStatus=Married
fcpdob=29/08/1984
fnationality=Indian
flegalStatus=Body Corporate
fresidentSt=Bank / Financial Institution_New
#fadhar=547687209641
#vidNo=3432424234234324
#faccType=Normal
fcorrAdr=HSR Layout Bengalore
fadrType1=Business
fcorrAdrType=India
fkycPincode=585328
forg=Sathya IFA-1
#fofficeTel=563464
#fresTel=874748
#freKyc=Yes
#fmobile=8833893987
#ffax=5342
fperiod=12 Months
femail=ram.c@rupeelog.com
fpermAdr=Bhalki Bidar KA
fadrType2=Business
fpermAdrType=India
fpermPincode=585328
fanyInf=contact us when required

#KyphFCP extra fields from KYPH
fcreateFCPDD=Yes
fOrganisationDD=Sathya IFA-1


#KyphFCP FATCA  
fReKYC=Yes
fgPanNo=AKGPC5014N
fgname=Ramesh
fgrel=Brother
fperiodDD=12 Months
fadrType=Business
fbirthPlace=bhalki
fbirthCtry=INDIA
fappIncomVl=>10 <= 25 Lacs
foccup=Service
fsourceOfIncome=Ancestral Property
ftotNetWorth=2
fnetWorthAsOn=06/10/2020
fpep=Not Applicable
fanyotherInfo=valid data
fcTxRes1=INDIA
ftaxID1=AKGPC8277N
fidType1=PAN card
fcTxRes2=INDIA
ftaxID2=AKGPC1177N
fidType2=PAN card
fcTxRes3=INDIA
ftaxID3=AKGPC9277N
fidType3=PAN card
fcTxRes4=INDIA
ftaxID4=6577
fidType4=Company Identification Number  issueOccured


# KyphFCP Specific

fsalutation=Mr
friskProfInvetPlcy=High Risk
friskProfPMLAPlcy=High Risk
fdoeCltHavAsset=Yes
fclientOrg=Rupeelog

# KyphFCP KRA Status

fcdsl=On Hold
fnsdl=On Hold
fdotex=On Hold
fcams=On Hold
fkarvya=On Hold
fannivDate=06/10/2020
fdobSpouse=06/10/2000
fdefAdr=Permanent Address
fdateCommen=06/10/2020
fuid=123454326546




############################################################################################################
							#####  PORTFOLIO DATA  ######
############################################################################################################
clieintNameAutoSuggSearch=test
selectClient=IA149499_JJSPL4785K_Automation Testing_Automation Testing
portfolioTypeDD=Executionary
EngagementTypeDD=Discretionary PMS
EngagementSubTypeDD=Basket
modelPortfolioSchemeDD=ISEQY
#advisorDD=
conversionDate=06/10/2020
name=Ram Portfolio8
sebiReportingTypeDD=Discretionary
reportFrequencyDD=Annual
#defaultBankDD=
#defaultDemat=
#pisBankDD=
statusDD=Active
advAgreementDD=Yes
currencyDD=Indian Rupees
custodianCodeDD=HDFC Bank
startDate=06/10/2020
EndDate=15/10/2020
BSE_MFDdate=15/09/2020
BSE_MFIdate=15/09/2020
reason=stock fall
ipsReqdDD=Yes
brokerEquityCode=1591
brokerMFCode=1592
BSE_MFDUCC=1593
BSE_MFIUCC=1594
brokerDebtCode=1596
brokerCommodityCode=1596
brokerOtherCode=1597
isMigratedDD=Yes

# ACCOUNTING

filepath=D:\\TestData\\Voucher_upload_template.xlsx

############################################################################################
# AddInvestmentAccountTest 
############################################################################################
familyNameAutoSuggSearch=Automation
selectfamily=Automation Testing Family (UCIC153732)_FRN_148431
selectInvestorType=Individual
clientGlobalCode=1010
primaryKyphAutoSuggSearch=Automation
selectPrimaryKyph=JJSPL4785K - Automation Testing - UCIC153732
selectheadOfFmlyDropDown=Yes
secondaryKyphAutoSuggSearch=Automation
selectSecondaryKyph=JJSPL4785K - Automation Testing - UCIC153732
tertiaryKyphAutoSuggSearch=Automation
selectTertiaryKyph=JJSPL4785K - Automation Testing - UCIC153732
statusDropDown=Active
selectAccountType=Executionary
selectClientEngagement=Gold
selectaddlStatusDropDown=No
corrAddress1=#401 HSR layout
IAcorrAdrType=India
corrPinCode=585328
selectDefAdr=Address 1 
contactOTName=Ram Chennale
contactOTLandlinePh=626161
contactOTEmail=ram.c@rupeelog.com
contactOTMobile=9977662211
namePOA=Ram
phoneRPOA=1234567890
phoneOPOA=1234567891
mobile1POA=1234567892
mobile2POA=1234567893
faxPOA=4321
email1POA=ram.c@rupeelog.com
email2POA=ram.c1@rupeelog.com
#------------------------Nomination-------------------------
nName=Raju
nomineeDOB=20/08/2000
selecNRel=Brother
nguardian=Rakesh
naddress=HSR layout Bengaluru
ncity=Bengaluru
npinCode=560102
nlandLin1=654653
nlandLin2=654654
nfax=42343
nmobile1=9922838811
#---------------guardian address----------------
gAddress=HSR layout Bengaluru
gCity=Bengaluru
selectGCountry=INDIA
gPincode=502102
gLandline1=434232
gLandline2=634534
gFax=4423
gMobile=834877362
#----------------RM Note Background----------------
investExper=5
selectRiskToleranDropdown=Low
annualIncomefrmOcc=1
estimatedIncomeFromOtherSrc=1
rmNote=Income as per annual
rmNote=Income as per annual
clientBackg=SBI and SBH
amountBeingInvested=1
expectedAUM=1
clientReferal=RBI
selectRepFre=Annual
selectIpsReq=Yes
selectRegGST=Yes
effectDateCal=17/07/2017
gstNum=GST76483268
selectSEZtype=SEZ














