############################################################################################################
#						 
employeeAutoSuggSearch=Ram
selectEmp=Ramesh KumarSAT198
newPassword=password
confirmPassword=password
############################################################################################################
#
KYPHAutoSuggSearch=Ram
selectKYPH=RCBDE0026P - Ram3 last3 - UCIC153778-RCBDE0026P
newKYPHPassword=password
confirmKYPHPassword=password

#User Role Access
empRoleAssignAutoSuggSearch=Ram
selectEmpToAssignRole=Ramesh KumarSAT198


#
docUploadKYPHAutoSuggSearch=Ram 
selectDocUploadKYPHAutoSuggSearch=ESLLL5874L - Ram Kumar - UCIC180392
docUploadDocTypeDD= Credit cards/Debit Cards issued by Banks
docUploadChooseFile=C:\\Users\\Ram\\eclipse-workspace\\WealthWeb\\DataFiles\\testImage.jpg

#Document Verification
searchKYPH=UCIC153550

#family comment
familyNameAutoSuggSearch=Ram 
selectfamilyNameAutoSuggSearch=Ram Family (UCIC180392)_FRN_17838
commentTypeDD= Comment 2
commentTextBox= Family comment

#View kyph Document
ViewkyphAutoSuggSearch= all txn
selectViewkyphAutoSuggSearch=QQAMA7845P - all txn - UCIC153550


#
druploadChooseFile=C:\\Users\\Ram\\eclipse-workspace\\WealthWeb\\DataFiles\\testImage.jpg
drfileTypeDD=Bank Statement
drTaggingLogicDD=CRN code
drTaggingSubLogicDD=Full filename
drStmtPrdFromDate=01/02/2021
drStmtPrdToDate=01/02/2021


#Generate NAV
gnFamilyNameAutoSuggSearch=all txn
selectgnFamilyNameAutoSuggSearch=all txn's Family (UCIC153550)-FRN_148323
gnStartDate=01/02/2021
gnEndDate=01/02/2021


#Rerun Commodity Future M2M
cmdityFturM2MPortfolioAutoSuggSearch=all txn
selectcmdityFturM2MPortfolioAutoSuggSearch=IA149389E149385_QQAMA7845P_all txn_all txn
cmdityFturM2MstartDateClient=01/02/2021
cmdityFturM2MstartDateAllClient=01/02/2021

#Rerun Currency Future M2M
currencyFutureM2MPortfolioAutoSuggSearch=all txn
selectcurrencyFutureM2MPortfolioAutoSuggSearch=IA149389E149385_QQAMA7845P_all txn_all txn
currencyFutureM2MstartDateClient=01/02/2021
currencyFutureM2MstartDate2AllClient=01/02/2021

#Rerun Currency Option Auto Expiry 
currencyOptPortfolioAutoSugg=all txn
selectcurrencyOptPortfolioAutoSugg=IA149389E149385_QQAMA7845P_all txn_all txn
currencyOptStartDate1Client=02/02/2021
currencyOptStartDate2AllClient=02/02/2021

#Rerun DPMS TWRR for Model portfolio
DPMSmodelPortfolioDD=ISEQY
DPMSstartDate=02/02/2021
#Rerun DPMS TWRR for portfolio
DPMSportfolioAutoSugg=Ram
selectDPMSportfolioAutoSugg=IA149530_RCBPC8226N_Ram Apparao Chennale_Ram Apparao Chennale_IA149530D17


#Rerun Equity Devidend client Test
edPfolioAutoSuggclient=all txn
selectedPfolioAutoSuggclient=IA149389E149385_QQAMA7845P_all txn_all txn
edStartDate1client=02/02/2021
#Rerun Equity Devidend Equity Test
edEquityAutoSugg=Birla
selectedEquityAutoSugg=Birla Cable Limited_BSE(500060)_NSE(BIRLACABLE)
edEquityStartDate2=02/02/2021
#Rerun Equity Devidend Client Equity Test
edCEpFolioAutoSugg=all txn
selectedCEpFolioAutoSugg=IA149389E149385_QQAMA7845P_all txn_all txn
edCEequityAutoSugg=Birla
selectedCEequityAutoSugg=Birla Cable Limited_BSE(500060)_NSE(BIRLACABLE)
edCEStartDate3=02/02/2021
#======================================

#Rerun Equity DMA client Test
eqDMAPfolioAutoSuggclient=all txn
selecteqDMAPfolioAutoSuggclient=IA149389E149385_QQAMA7845P_all txn_all txn
eqDMAStartDate1client=02/02/2021
#Rerun Equity DMA Equity Test
eqDMAEquityAutoSugg=Birla
selecteqDMAEquityAutoSugg=Birla Cable Limited_BSE(500060)_NSE(BIRLACABLE)
eqDMAEquityStartDate2=02/02/2021
#Rerun Equity DMA Client Equity Test
eqDMACEpFolioAutoSugg=all txn
selecteqDMACEpFolioAutoSugg=IA149389E149385_QQAMA7845P_all txn_all txn
eqDMACEequityAutoSugg=Birla
selecteqDMACEequityAutoSugg=Birla Cable Limited_BSE(500060)_NSE(BIRLACABLE)
eqDMACEStartDate3=02/02/2021

#======================================

#Rerun future M2M for single client
futureM2MPfolioAutoSugg=all txn
selectfutureM2MPfolioAutoSugg=IA149389E149385_QQAMA7845P_all txn_all txn
futureM2MstartDate1Client=03/02/2021
#Rerun future M2M forAll client 
futureM2MstartDate2AllClient=03/02/2021

#Rerun Realised Gain for Portfolio
rgpfolioAutoSugg1=all txn
selectrgPfolioAutoSugg1=IA149389E149385_QQAMA7845P_all txn_all txn
#Rerun Realised Gain for Portfolio and Asset combination
portfolio=all txn
selectPortfolio=IA149389E149385_QQAMA7845P_all txn_all txn
rgUnderScript=muthoot
rgfutureListDD=muthootfin - NSE
rgexpiryDD=Apr-18


#Run MF fifo folio wise
RunMFfifofoliowiseSDate=03/02/2021
RunMFfifofoliowiseEDate=03/02/2021

#Update KYC Status
verifyKYCdd=Update Manually
panNumber=QQAMA7845P

#XIRR
familyName=all txn
selectfamilyName=all txn's Family (UCIC153550)_FRN_148323
xirrStartDate=02/02/2021
xirrEndDate=03/02/2021

#Mapping
# Create Client-IPS Mapping
fcpTypeDD=Client
clientName=all txn
selectClientName=IA149389_QQAMA7845P_all txn_all txn
riskTypeDD=Low
effectiveDate=06/02/2021
min=10
max=100
Restricted/NRestInvest=Restricted
EqMarketCapMin==10
EqMarketCapmax=100
DebtPrudentialNormsVal=10
PortfolioLevelVal=100

#Create Family Benchmark mapping
fbmBenchmarkDD=BANK NIFTY
fbmEffectiveDate=06/02/2021

# Family RM mapping
rmfamilyAutoSugg=all txn
selectrmfamilyAutoSugg=IA149389_QQAMA7845P_all txn_all txn
rmselectRMname= Ramesh Kumar ( SAT198 )
rmStartDate=01/02/2021
rmEndDate=06/02/2021


#RM Family Mapping Upload
ChooseRMfmlyMappingFile=C:\\Users\\Ram\\eclipse-workspace\\WealthWeb\\uploadFiles\\FamilyRMMappingTemplate.xlsx

#Organization
#Employee
empFirstName=Ram003
empMiddleName=MNRam003
empLastName=LNRam003
empCode=ram003
empExtdesignDD=Asst Manager
empEmail=ram.c@rupeelog.com
empLogin=ram003
empPassword=password
empStatus=Active
empStartDate=08/02/2021
empSubType=RM
empOrgn=Sathya IFA-1

#Employee reporting mapping and 
erEmpAutoSugg=Ram003
selecterEmpAutoSugg=Ram003 LNRam003(ram003)
erReportingEmpAutoSugg=ram
selecterReportingEmpAutoSugg=Ramesh Kumar(SAT198)
erstartDate=08/02/2021

#Linked Employee
leEmpAutoSugg=Ram003
selectleEmpAutoSugg=Ram003 LNRam003(ram003)
leLinkedEmpAutoSugg=ram
selectleLinkedEmpAutoSugg=Ramesh Kumar(SAT198)
leRelationTypeDD=View Client Reports

#Reporting Organization Tree
Employee=sat
selectEmployee=Sathya HK(SAT001)

#Password
# MF Exchange Password
mfPwdEntityDD=SRM
mfPwdExchangeDD=BSE
mfPwdTypeDD=MFD
mfPwdUserid=10026
mfPwdMemberid=10126
mfPwdPassword=password

#rta Email Password
rtaArnDD=ARN-0009
rtaCamspwd1=cams123
rtaKarvypwd1=karvy123
rtaFranklinpwd1=frank123
rtaSundarampwd1=sund123
rtaHost=imap.gmail.com
rtaPort=6666
rtaUsername=rama@rupeelog.com
rtaPassword=password

#Tenant Payment Expiry
tnTenantDD=SRM
tnEmpExpDate=01/02/2022
tnEmpExpMsg=Feb 2022
tnEmpWarnDaysDD=90
tnEmpWarnMsg=NintyDays
tnKYPHExpDate=01/02/2030
tnKYPHWarnMsg=Feb 2030
tnKYPHWarnDaysDD=90
tnKYPHWarnMsg=NintyDays
tnStatusDD=Active





