############################################################################################################
#						 
############################################################################################################
#Masters
#Asset Master
AssetCombo=Asset Combo
HouseRecommendation=House Recommendation
InvestmentHorizon=Investment Horizon
InvestmentStrategy=Investment Strategy
MarketCap=Market Cap
Risk=Risk
Mapping=Mapping

#Bank DP Broker
BankAccountType=Bank Account Type
BankMaster=Bank Master
Branch=Branch
Broker=Broker
BrokerBank=Broker Bank
BrokerDemat=Broker Demat
DPMaster=DP Master

#COB Master
LegalStatus=Legal Status
Occupation=Occupation
ResidentialStatus=Residential Status

#Common Master
CaliberSchedulerNotification=Caliber Scheduler Notification
EmailCreden=Email Creden
IndicesBenchmarkValues=Indices / Benchmark Values
OrganisationOrdermode=Organisation Ordermode
OrgnBSEEnable=Orgn BSE Enable
SMSCreden=SMS Creden
StandardRemarks=Standard Remarks

#ManagedAccount
ManagedAccountAdvisor=Managed Account Advisor

#MutualFund
AssetManagementCompany=Asset Management Company
MFClassification=MF Classification
MFFundManager=MF Fund Manager
RegistrarRTA=Registrar(RTA)
RTATxnTypeMapping=RTA Txn Type Mapping

#OrganizationMaster
omBranch=Branch
BranchCategory=Branch Category
Cluster=Cluster
CounterParty=Counter Party
Department=Department
Designation=Designation
EmployeeCertificate=Employee Certificate
Organization=Organization
Region=Region
Zone=Zone

# System Master 
ARN=ARN
AutoJobLog=AutoJob Log
AutoJobSetUp=AutoJob SetUp
City=City
GLAccountMapping=GL Account Mapping
GSTMaster=GST Master
State=State
TaxTypeRate=Tax Type Rate
Country=Country

#ADMIN
#Access Control
AssignResource=Applicable Permission
ChangeEmployeePassword=Change Password
ChangePassword=Change Password
ChangPasswordKyph=Reset KYPH Password
Role=Role
UserRoleAccess=User-Role Access

#COB
BSEAof=BSE AOF
BSEStarFatca=BSE Star Fatca Creation
BSEStarUCC=BSE Star Client UCC Creation
DocumentUpload=Document Upload
DocumentVerification=Document Verification
Family=Family
FamilyComments=Financial Advisor Comments
InvestmentAccount=Investment Account
KYPH=KYPH
Portfolio=Portfolio
ViewKyphDocuments=View Kyph Documents

#Delete Report Scheduler
DeleteReportScheduler=Delete Report Scheduler

#DocRepository
DocRepository=Upload

#Manual Txn Adjustments
CommodityFutureTxnDelete=Commodity Txn Delete
CurrencyFutureTxnDelete=Currency Future Txn Delete
mtaFutureTxnDelete=Future Txn Delete
GenerateNav=Generate NAV
RerunCommodityFutureM2M=Rerun Commodity Future M2M
RerunCurrencyFutureM2M=Rerun Currency Future M2M
RerunCurrencyOptionAutoExpiry=Rerun Currency Option Auto Expiry
RerunDPMSTWRR=Rerun DPMS TWRR
RerunEquitydividend=Rerun Equity Dividend
RerunEquityDMA=Rerun Equity DMA
RerunEquitySplitBonus=Rerun Equity Split Bonus
RerunFutureM2M=Rerun Future M2M
RerunRealisedGain=Rerun Realised Gain
RunMFfifofoliowise=Run Mf Fifo folio wise
UpdateKYCStatus=Verify Kyc
VoucherDelete=Voucher Delete
Xirr=Xirr
XirrSinceInception=Xirr

#Mappings
ClientBankMapping=Client Bank Mapping
ClientDematMapping=Client Demat Mapping
ClientIPSMapping=Client-IPS Mapping
FamilyBenchmarkmapping=Family Benchmark mapping
FamilyRMMapping=Family RM Mapping View
FamilyRMMappingsUpload=Family RM Mappings Upload

#Organization
Employee=Employee
EmployeeReportingMapping=Employee Reporting Mapping
LinkedEmployee=Linked Employee
ReportingOrganizationTree=Reporting Organization Tree 

#Password
MFExchangePassword=MF Exchange Password
RTAEmailPassword=RTA Email Password

#PingRefresh
PingRefresh=Ping

#System Lock
SystemLock=System Lock

#TenantPaymentExpiry
TenantPaymentExpiry=Tenant Payment Expiry
############################################################################################################
# Instrument						 
############################################################################################################
insDebtInstrument=Instrument
MarketValues=Market Values

#Instrument Derivatives
SpanMargin=Span Margin
SpanMarginView=Span Margin View
FuturePrice=Future Price
OptionsPrice=Options Price
OptionsScrip=Options Script

#Instrument Equity
Buyback=Buyback
CABonusSplit=CA-Bonus/Split
CADividend=CA - Dividend
CAMergerDeMerger=CA - Merger, DeMerger
ClosingPrices=Closing Prices
Delisting=Delisting
IPOFPO=IPO/FPO
OpenOffer=Open Offer
RightsIssue=Rights Issue
Scrip=Scrip

#Instrument Managed Account
ManagedAccountFund=Managed Account Fund
ManagedAccountMarketvalue=Managed Account Market value
ManagedAccountScheme=Managed Account Scheme

#Instrument MF
CAMerger=CA - Merger View
MutualFundNAVs=Mutual Fund NAVs
MutualFundNFO=Mutual Fund NFO
MutualFundScheme=Mutual Fund Scheme


#Order
#Debt 
BuySellWithRisk=Buy Sell
BuySellWithoutRisk=Pre Order Buy Sell Without Risk
IPO=IPO

#Fund Payout Order
FundPayoutOrder=View All Payout Order 

#ManagedAccounts
maBuySellWithRisk=Buy Sell
maBuySellWithRiskNew=BuySellWithRiskNew
maBuySellWithoutRisk=Pre Order Buy Sell Without Risk
maIPO=IPO

#Mutual Fund
BuySell1=Buy Sell
BuySellSwitchCart1A=Cart Order View
SystematicPlanCart1B=Cart Sysplan View
Mandate=Mandate

#Pre Order Equity
preOrderEquity=Pre Order-Equity

#Reports
AdhocReports=Adhoc Reports
BulkSMS=Bulk SMS Sending
ChartAnalytics=Chart Analytics
DailySalesReports=Daily Sales Reports(DSR)
DebitCreditNote=Debit/Credit Note
KyphEmail=Sending Emails to Kyph
LargeReportExecute=Large Report Execute
MultiReportDownloadEmail=Report Download & Email
MultiReportGeneration=Multi-Report Generation
PushNotification=Push Notification
ReportingServer=Browse Repository
RMReports=RM Reports
TxnSearch=Transaction Search

#RIMS
#Client Fees
PostingDayMaster1=Posting Day(Master)
FeesPostingFrequencyMaster2=Fees Posting Frequency(Master)
FeesRulesUpload3=Fees Rules Upload
CalculateFees4=Calculate Fees
CalculatedFeesDetails5=Calculated Fees Details
FeePosting6=Fee Posting
IntegFeesCreateRule7a=7a. Integ.Fees-Create Rule
IntegFeesCalculate7b=7b. Integrated Fees-Calculate
IntegFeesPostFees7c=7c. Integ.Fees-Post Fees
PerformanceFees8=8. Performance Fees

#MF Revenue
MFRateCardUpload1a=MF Rate card Upload
MFRateCardExceptionUpload1b=MF Rate Card Exception Upload
MFFeesCalculation2a=MF Fees Calculation
MFFeesExceptionCalculation2b=MF Fees Exception Calculation
RTARevenueFiles3=RTA Revenue Files
TrailForecasting4=Trail Forecasting View
AMCCommissionReceipt5=5. AMC Commission Receipt
RevTypeMaster=Rev Type Master
RTARevTypeMapping=RTA Rev Type Mapping
SIPRateCardUpload=SIP Rate Card Upload
SwitchRateCardUpload=Switch Rate Card Upload

#Non MF Revenue
NonMFRateCardUpload1=Non MF Rate card Upload

#Other Revenue
Brokerage=Brokerage
BrokerageValidate=Brokerage Validate
RevenueMiscUpload=Revenue Misc Upload

#RIMS Misc
ExpenseSalaryUpload=Expense Salary Upload
InternationalAUM=International AUM
KRABasedTarget=KRA Based Target
ServiceRMRMLinkage=Service RM-RM Linkage

#RIMS Update
FamilywiseSplitMaster=Family-wise Split Master
MFRateCardDelete=MF Rate Card Delete
MiscCaln=RIMS Rerun
RIMSTxnDelete=RIMS Txn Delete
RMWiseRevSplitB=RIMS B

#Rims Upload
UploadProcess=Upload Process


#Process
#AutoRequest
AutoRequest=Auto Request

#Bank
BankStatementRecon=Bank Reconciliation

#Broker 
BrokerLedgerTxnNotValidated=Broker Ledger Txn-Not Validated
FetchBrokerLedgerBalance=Fetch Broker Ledger Balance
FetchBrokerLedgerTxns=Fetch Broker Ledger Txns
FetchBrokerStockBalance=Fetch Broker Stock Balance

#Commodity Txn - Not Validated
CommodityTxnNotValidated=Commodity Txn - Not Validated

#Confirmation
Recommendation=Recommendation
RecommendationNew=RM Recommendation
ValidateVouchers=Equity Error Txn - Exec/Exec(POA)

#Currency
CurrencyTxnNotValidated=Currency Txn - Not Validated

#Debt
DebtPrice=Create Market Value

#Delete Error Txns
DeleteErrorTxns=Delete Error Txns

#Derivative
DerivativeErrorTxnExec=Derivative Error Txn - Exec/Exec(POA)

#Eod and Dashboard
EodProcessDashboard=Eod Process Dashboard
ProcessDashboard=Process Dashboard
RunEodProcess=Run Eod Process


#Equity
EquityErrorTxnExec=Equity Error Txn - Exec/Exec(POA)
FetchPricesforEquityMasters=Fetch Prices for Equity Masters

#File Process And DashBoard
FileProcessDashBoard=View/
ProcessedFileDownload=View/
RunFileProcess=View/

#IndicesBenchmark
IndicesBenchmarkValues=Indices / Benchmark Values

#Managed Account txn
MAFolioChange=Change Folio(MA/Debt)
ManagedAccountMarketValue=Managed Account Market value
OrderMatching=Order Matching
VCFCommittedInvestmentUpload=VCF Committed Investment Upload

#Mutual Fund
AUMUploadRTA=Aum Recon
FolioMapped=Folio Mapped
FolioUnmapped=Folio Unmapped
MasterPullBSEStar=Master Pull BSE Star
MfFolioChange=Mf Folio Change
MFfolioPortfolioShift=MF folio Portfolio Shift
MFRTACorpusNotValidated=MF RTA Corpus - Not Validated
MFTransactionNotValidated=MF Transaction - Not Validated
TransactionOrderMatching=Transaction Order Matching
TransactionUploadRTA=Transaction Upload RTA
UploadAmfiNAV=Upload Amfi NAV
ValidateSIPErrorEntries=SIP Error Txn
ValidateWbr9Error=Validate WBR9

#Upload Process
GeneralUpload=Document Upload
PullfromView=Pull from View
Revalidate=Revalidate
SpecificUpload=Specific Upload

#Accounting
CorpusCashInOut=Corpus Cash In-Out
CorpusInOutUpload=Corpus In/Out Upload
CorpusStockInOut=Corpus Stock In-Out
ManagedAccTxnUpload=Managed Acc Txn Upload
ManualVoucher=Manual Voucher
VoucherUpload=Voucher Upload

#Disc PMS
#Client Management
CorpusOutRequestView=Corpus Out Request View
FreezePortfolio=Freeze Portfolio
NegativeList=Negative List

#Model Portfolio
CompositionUpload=Composition Upload
ModelPortfolioScheme=Model Portfolio Scheme
SchemeAlternateList=Scheme Alternate List

#Orders
GenerateVariance1=Generate Variance
VarianceforAccountingPortfolio2=Variance For Accounting Portfolio
PrepareOrders3=Prepare Orders
PrepareAlternativeInvestOrders4=Prepare Alternative Invest Orders
PlaceOrders5=Place Orders


#Settlement
#Debt
dSettleCash=Settle Cash
dSettleStock=Settle Stock

#Equity
eSettleCash=Settle Cash
eSettleStock=Settle Stock

#Managed Account
maSettleCash=Settle Cash

#Mutual Fund
mfSettleCash=Settle Cash
mfSettleStock=Settle Stock

#Option (Derivative)
CustodianSettleCash=Settle Cash

#Held Away
TransactionUpload=Transaction Upload


#FP Admin
AssetSubClassGrowthEstimate=Asset Sub Class Growth Estimate
FPSystemParam=Financial System Parameters
HouseRecoAssetSubclass=House Recommendation
InstrumentGrowthEstimate=Instrument Growth Estimate
InsurancePolicy=Insurance Policy
InsuranceProvider=Insurance Provider
ModelPortfolioFP=Model Portfolio

#Financial Planning
AdditionalInvestmentPlanning=Plan Additional Investment for Goal
AssetSubClassToGoalLinkage=Investment class to goal linkage
FinancialAdvisorComments=Financial Advisor Comments
GeneratePlan=Generate Plan
GoalInvestmentLinkage=Goal Investment Linkage
InsurancePlanningNew=Insurance Recommendation View
RedemptionPlan=Redemption
ReportingCategoryGoalLink=ReportingCategory Goal Link

#Finplan Input
Expense=Expense
Goal=Goal
Income=Income
RiskQuestionnaireKyph=Risk Questionnaire

#Investment
CommittedInvestment=Committed Investment
CommittedInvestmentNew=Committed Investments
FDandRD=FD and RD
Insurance=Insurance
Liability=Liability
RealEstateandOthers=Real Estate and Others
RealEstateMarketPrice=Real Estate Market Price
TransactionUpload=Transaction Upload

#Operations
#Uploads
DocumentDownload=Document Download
DocumentUpload=Document Upload








