#Home/Disc PMS/Client Management/Corpus Out Request View
#CreateCorpusOutReqTC
coReqPortfolioAutoSugg=ram chennale
selectcoReqPortfolioAutoSugg=
coReqCorpusOutDate=
coReqCorpusOutAmount=
coReqRemarks=

#Home/Disc PMS/Client Management/Freeze Portfolio
#CreateFreezePortfolioTC
freezPortfolioAutoSugg=ram 
selectfreezPortfolioAutoSugg=IA149530_RCBPC8226N_Ram Apparao Chennale_Ram Apparao Chennale_IA149530D17
freezStartDate=10/03/2021
freezEndDate=10/03/2021
freezBuyDD=Yes
freezSellDD=No
freezDescription=freezing portfolio


#Home/Disc PMS/Client Management/Negative List 
#CreateNegativeListTC
nlClientNameAutoSugg=ram
selectnlClientNameAutoSugg=IA149562_RCBDE0030P_Ram8 Apparao8 chennale8
nlAssetClassDD=Equity
nlEquityNameAutoSugg=birla
selectnlEquityNameAutoSugg=Birla Cable Limited_BSE(500060)_NSE(BIRLACABLE)
nlStartDate=10/03/2021

#Home/Disc PMS/Model Portfolio/Model Portfolio Scheme
#CreateModelPortfolioSchemeTC
mpsName=Ram MP
mpsCode=0026
mpsOrgnDD=Sathya IFA-1
mpsRisksDD=High Risk
mpsStatusDD=Active
mpsBenchmarkDD=BANK NIFTY
mpsBasis=ITES
mpsCustodyProviderDD=Axis
mpsCustodyCode=1026
mpsContingencyCash=90
mpsStartDate=12/03/2021
mpsEndDate=12/03/2022
mpsDescription=model PF
mpsAmount=1000
mpsIsMfRegularAllowDD=No
mpsIsUnlistedEqAllowDD=No

#Home/Disc PMS/Model Portfolio/Scheme Alternate List
#CreateSchemeAltListTC
#ViewSchemeAltListTC
saPortfolioNameAutoSugg=ram model
selectsaPortfolioNameAutoSugg=Ram Model Portfolio Scheme(1026)
saAssetClassDD=Debt
saIssuerDD= A. K. CAPITAL FINANCE PRIVATE LIMITED
saInstNameDD= A. K. CAPITAL FINANCE PRIVATE LIMITED SR-A-I 9.6 LOA 07MR22 FVRS1LAC(INE197P07011)
saStartDate=12/03/2022
saEndDate=12/03/2022
sacomment= comment

#Home/Disc PMS/Order/Generate Variance
#GenerateVarianceTC
gvChooseModelPortfDD=ISEQY

#Home/Disc PMS/Order/Variance For Accounting Portfolio
#ViewVarianceForAccPortfolioTC
varianceAccPortfolioAutoSugg=ram
selectvarianceAccPortfolioAutoSugg=IA149530_RCBPC8226N_Ram Apparao Chennale_Ram Apparao Chennale_IA149530D17

#Home/Disc PMS/Order/ Prepare Orders 
#PrepareOrdersViewTC
povChooseModelPortfDD=SATDPMS01


#Home/Disc PMS/Order/Prepare Alternative Invest Orders
#PrepareAltInvOrdViewTC
paioChooseScheme=SATDPMS01
paioChoosePortfolio= Vishal MP DPMS(IA140105D3)

#Home/Disc PMS/Order/Place Orders View
#PlaceOrdViewTC
povModelPortfolio=ISEQY


#Home/Disc PMS/Order/Cancel Orders
#CancelOrdTC
coChooseSchemeModelPortfoliosDD=ISEQY

#Home/Disc PMS/Confirm Allocation
#ConfirmAllocationTC
caStartDate=16/03/2021
caChooseScheme=ISEQY

#Home/FP Admin/Asset Sub Class Growth Estimate
#AddAssetGrowthRateTC
agrAssetSubclassDD= Aggressive Hybrid Fund
agrMeanGrowthRate=10
agrEffDate=16/03/2021
agrMin=10
agrMax=100
agrMedian=5
agrStandardDeviation=2
agrComment=Adding Aggressive Hybrid Fund asset


#Home/FP Admin/House Recommendation
#AddHouseRecdTC
hrAssetSubclassDD= AIF - DEBT
hrIssuer= A. K. CAPITAL FINANCE PRIVATE LIMITED
hrInstNameDD= Relience JIO
hrShortTermDD=1
hrMediumTermDD=1
hrLongTermDD=1
hrStatusDD=Active
hrComment=comment


#Home/FP Admin/Instrument Growth Estimate
#AddInstGrowthEstimateTC
igrAssetSubclassDD= Bonds
igrIssuerDD= ADITYA BIRLA FIN
igrInstDD= ADITYA BIRLA FINANCE LIMITED 78D CP 24OT13
igrMeanGrowthRate=10
igrEffDate=17/03/2021
igrMin=10
igrMax=100
igrMedian=5
igrStandardDeviation=2
igrComment=Adding Aggressive Hybrid Fund asset

#Home/FP Admin/Insurance Policy
#CreateInsuPolicyTC
ipProviderNameDD=LIC
ipPolicyName=life Insu Corp IND
ipActiveDD=Active
ipTypeDD=C
ipUIN=20005501
ipStartDate=01/03/2021
ipEndDate=17/03/2021
ipULIPDD=Y
ipDescription=lic insurance
ipTenure=12 month

#Home/FP Admin/Insurance Provider
#CreateInsuProviderTC
iproPolicyProvider=LIC India
iproAddress=Bengaluru
iproWebSite=www.rupeex.com
iproDescription=LIC India Insurance Provider



#ModelPotfolio
mpname=Ram MP
mpcode=1001	
mppriorityDD=Low
mpdurationDD=Short Term
mpstartDate=19/03/2021
mpuserRisk=Low
mpstatusDD=Active
mpcomments=comment










