############################################################################################################
#Instrument Debt/Instrument/Create Instrument
diIssuerDD=A. K. CAPITAL FINANCE PRIVATE LIMITED
diName=Relience JIO
diShortName=RIJIO
diAssetSubClassDD=AIF - DEBT
diRegistrarDD=Registrar
diPayingAgentDD=TestPaying Agent
diFaceValue=10
diMaturityDate=01/01/2030
IsVerifiedDD=No
IsManualIntDD=No
#Interest
iInterestRateDD=Fixed
iInterestPercent=5
iPaymentIntervalDD=Monthly
iInterestTypeDD=Simple
iCalculationMethodDD=Actual/Actual
iDeemedDateOfAllotment=01/01/2020
iIncludeIPDateDD=No
iIsTaxableDD=No
iFirstIPDate=01/01/2017
iNoDeliveryPeriodDays=30

############################################################################################################
#Instrument/Instrument Debt/Market Values
dpissurNameDD= 19.00% MID-CITY
dpInstNameDD= 19.00% MID-CITY INFRASTRUCTURE PRIVATE LIMITED(INE657S07042)
dppriceTypeDD=Clean Price
dpPrice=1000
dpPriceDate=11/02/2021
############################################################################################################
#Instrument/Instrument Debt/Market Values
muUploadFileBrowse=C:\\Users\\Ram\\eclipse-workspace\\WealthWeb\\uploadFiles\\DebtMarketPriceformat.xlsx

############################################################################################################
#Instrument/Instrument Derivatives/Span Margin
smBseNseDD=NSE
spMarginDate=12/02/2021
smUploadFileBrowse=C:\\Users\\Ram\\eclipse-workspace\\WealthWeb\\uploadFiles\\Span Margin format.xlsx
SpanMarginResult=Margins added

#Instrument/Instrument Derivatives/ Future price
fpUnderlyingScrip=muthoot
fpfutureListDD=muthootfin - NSE
fpExpiry=Apr-18
fpOpenPrice=850
fpClosePrice=860
fpPreviousDayClosePrice=855
fpHighAmt=1000
fpLowAmt=790

#Instrument/Instrument Derivatives/Option price
opOptionTypeDD=Call
opUnderlyingScripSearch=muthoot
opOptionListDD=muthootfin - CE - NSE
opStrikePriceDD=CE-280.0-Apr-18
opPriceDate=15/02/2021
opOpenPrice=900
opClosePrice=990
opHighAmt=1000
opLowAmt=890

#Instrument/Instrument Equity/BuyBack
bbEQnameAutoSugg=birl
selectbbEQnameAutoSugg=Birla Cable Limited(BSE-500060 ,NSE-BIRLACABLE)
bbStartDate=16/02/2021
bbEndDate=20/02/2021
bbComments=Mention the DP Details and Max Price
bbResearchRecoDD=Yes
bbResComments=comment

#CreateCASplitBonusTC
sbAssetSubClassDD= Equity - Listed
sbInstAutoSugg=birl
selectsbInstAutoSugg=Birla Cable Limited_BSE(500060)_NSE(BIRLACABLE)
sbTypeDD=Bonus
sbExDate=20/02/2021
sbNumNewBonusShare=500
sbNewFaceVal=12
sbOldFaceVal=10
sbSplitOldFaceVal=5
sbCorptActSeqDD=First

#CreateCADividendTC
cadAssetSubClass= Equity - Listed
cadScrip=birl
selectcadScrip=Birla Cable Limited_BSE(500060)_NSE(BIRLACABLE)
cadExDate=20/02/2021
cadDividendRsPerShare=100
cadCorpusActionSeqDD=Before Bonus and/or Split

#Create Merger/Demerger/Amalgamation
#Source
mdaChooseCorpActDD=Merger
mdaTransactionDate=06/02/2021
mdaHistoricLotsDD=No
mdaDetailsDDsrc=Source
mdaAssetSubClsDD= Equity - Listed
mdaInstrumentAutoSugg=birl
selectmdaInstrumentAutoSugg=Birla Cable Limited_BSE(500060)_NSE(BIRLACABLE)
mdaRatio=10
mdaValueWeightage=100

#Destination
mdaDetailsDDdst=Destination

#Intrument Managed Accounts
#MA Fund
mafName=Ram MAF
mafCode=SRMMAF
mafOrg=Sathya IFA-1

#Instrument MF/CA - Merger View
mfcaSrcSchemeAutoSugg=birl
selectmfcaSrcSchemeAutoSugg=BIRLA FTP-QUARTERLY SERIES 6-DIVIDEND(B826D)
mfcaTrgtSchemeAutoSugg=birl
selectmfcaTrgtSchemeAutoSugg=BIRLA SUN LIFE FIXED TERM PLAN - SERIES BH RETAIL GROWTH(B921RG)
mfcaExDate=16/02/2021
mfcaSrcNumUnit=1000
mfcatrgtNumUnit=500

#Mutual Fund NFO
nfoAmcDD=Aditya Birla Sun Life Mutual Fund
nfoNAME=Sri Ram
nfoAssetSubClassDD=Aggressive
nfoRtaNameDD=Cams
nfoMFtypeDD=Open-Ended
nfoOfferPrice=500
nfoClassification=Aggressive Hybrid Fund
nfoPlanType=Bonus
nfoOpenDate=16/02/2021
nfoFaceValue=10
nfoFundManagerNameDD=Karvy


#Mutual Fund scheme creation
mfsAmc=Aditya Birla Sun Life Asset Management Company
mfsSchemeName=Birla Life Insurence
mfsAssetSubClass=Aggressive Hybrid Fund
mfsMFtype=Open-Ended
mfsClassification=Aggressive Hybrid Fund
mfsPlanType=Bonus
mfsSchemeType=Direct
mfsStatus=Active
mfsCamsCode=CAMS002
mfsHoldToMaturity=No




































