############################################################################################################
#Bank Master
bankName=Bank Of KLD
bankShortName=BOK
address=Kalwadi Bhalki
bseStarMode=
bseStarCode=

############################################################################################################
#
bankNameDD=Sri Ram Bank
ifscCode=SRM0000002
micr=123456701
branchName=Bhalki
branchShortName=BLK
cityDD=Bengaluru South
address=Bhalki
		
############################################################################################################
#Create Broker Bank
custodianAccountDD=Yes
isDefaultBrokerBankDD=Yes
accountNo=123456785001
HolderName=Ram Chennale
bankNameDD=Sri Ram Bank
bankBranchNameAutoSuggSearch=HSR
SelectBankBranchName=HSR Layout
accountTypeDD=Current
isPoolAccountDD=No
statusDD=Active
############################################################################################################
#DP Master
dpName=SRMsys DP
dpID=1002
dpTypeDD=CDSL
dpAddress=Bhalki					
############################################################################################################




























































