############################################################################################################
#Email Creden creation
orgnDD=SRM
emailSenderName=srmmf@caliber.com
emailCaption=srm mf support
userName=apikey
password=password
host=smtp.sendgrid.net
port=25
############################################################################################################
#Create Indices / Benchmark Values
IndicesName=LIC India
selectassetSubClassDD=Real Estate
code=ILIC000001		
############################################################################################################
# Organisation Order mode
orgnDD=SRM
priority1=BSEMFD
priority2=BSEMFD

############################################################################################################
#Create Orgn BSE Enable
orgnDD=SRM
isCtfEnable=No
ctfDirect=Yes
ctfRegular=Yes
isMfiEnable=Yes
mfiDirect=Yes
mfiRegular=Yes
isMfdEnable=Yes
mfdDirect=Yes
mfdRegular=Yes
############################################################################################################
#SMS Creden
orgnDDSMS=SRM
usernameSMS=uat
passwordSMS=password
senderName=Rlogfs
authURL=http://api.unicel.in/SendSMS/sendmsg.php

############################################################################################################
#
maAdviserName=Ram Chennale MAA
maAdviserShortName=RCMAA
email=ram.c@rupeelog.com


#MF Classification
MFClassificationName=EquityEQ
isLiquidDD=Yes
MFClassificationShortName=EQMF
MFClassificationSubCategory=EQMutualFund


#AMC
amcName=Sri Ram AMC
amcShortName=SRAMC
address1=Bengaluru
stateDD=KARNATAKA
pinCode=510560
camsCode=CAM291
gstRegisteredDD=No


#
mfFundManagerName=Ram MFMgr
biography=Stock Br

#
rtaNameDD=Cams
rtaTxnType=CamsTxn
rxTxnTypeDD=Buy
displayDetails=CAMSBUY
isReversalDD=No


#Organization Master
branchCategory=HO
branchName=Hyderabad
branchShortName=Hyd
cityAutoSuggSearch=Bengaluru
selectCity=Bengaluru South
headBranch=Pune
address1Branch=Bengaluru
regionBranch=Agra
clusterBranch=SouthWest
orgBranch=Sathya IFA-1

#Branch Category
branchCategoryName=Software Services
branchCategoryShortName=ITES


#Cluster
nameCluster=SouthEast
codeCluster=SECL
startDateCluster=25/01/2021
endDateCluster=25/01/2022
ClusterRegionDD=Agra
ClusterOrgn=Sathya IFA-1


#counter party
cpname=RupeeXC
cpcityautoSuggSerch=bengaluru
cpSelectCity=Bengaluru South
cpbankNameDD=Abhyudaya Cooperative Bank
cpbranchDD=RTGS-HO
cpAccountName=RxRam
cpaccountNo=147852369
cpaccountTypeDD=Current
cpparticipantNameDD=1001(SRMDP)
cpdematNo=123654


#Department 
departmentName=Mutual funds
departmentshortName=AMFI
departmentType=Service

#Designation
designationName=Chief Tech Off
designationShortName=CTO

#Emp certificate
certificateName=QA Certified
certificateShortName=STQA


#Organization
orgName=RupeeX
orgShortName=Rux
orgFrnCode=RxFRN
orgCrnCode=026
orgState=MAHARASHTRA

#City
smCityName=Bhalki
smCityShortName=BLK
smCityStateDD=KARNATAKA
smCityRegion=North Karnataka
smCityCAMScode=CM1021


#Country
CountryName=Bharat
CountryShortName=BRT
CountryCamsCode=CAM1021


#GST
effectiveDate=28/01/2021
gstStateDD=KARNATAKA
cgst=9.00
sgst=18.00
igst=2.00
cess=0.010
mFCommnAppDD=No
typesDD=Mf International
remarks=Tax slab

#state
stateName=United Bharat
stateShortName=USB
stateCountryDD=INDIA
stateCode=91
stateTypeDD=State

















