#################################################################################################
#Asset Combo master
Name=Birla AC
AssetComboCode=BAC01
typeDD=Both
RiskTypeDD=High
InvHorizonTypeDD=0 - 7 Days
ClassificationDD=2-Debt|DB
IsTaxSavingDD=Yes
isDirectDD=Yes
BenchmarkDD=BANK NIFTY
StartDate=01/09/2020
EndDate=01/11/2022
remarksTextArea=Good to have
#ImagePath=
orgnDD=Sathya IFA-1


#################################################################################################
#Create House Recommendation
houseReco=Six Star
houseRecoCode=C06
#################################################################################################
#investment Horizon

investmentHorizon=20+
investmentHorizonCode=C12
#################################################################################################
#Create Investment Strategy
invStratergy=Decade
invStratergyCode=C13

#############################################
#Risk
riskParameter=Risky
RiskCode=C07
sequence=7
minScore=10
maxScore=101

#############################################
#Risk-IPS Mapping
riskTypeDD=High
effectiveDate=06/04/2020
norm1Min=10
norm1Max=100
norm2Min=10
norm2Max=100
norm3Min=10
norm3Max=100
norm4Min=10
norm4Max=100
norm5Min=10
norm5Max=100
norm6Min=10
norm6Max=100
Norm7DD=Restricted
Norm8DD=Restricted
Norm9DD=Restricted
Norm10DD=Restricted
Norm11DD=Restricted
Norm12DD=Restricted
norm13Min=10
norm13Max=100
norm14Min=10
norm14Max=100
norm15Min=10
norm15Max=100
norm16Min=10
norm16Max=100
norm17Min=10
norm17Max=100
norm18Min=10
norm18Max=100
Norm19=10
Norm20=10
Norm21=10
Norm22=10
Norm23=10
Norm24=10
Norm25=10
Norm26=10
Norm27=10
Norm28=10
Norm29=10























































