############################################################################################################
#Legal Status
selectinvestorTypeDD=Non Individual
legalStatusName=NGO Social
legalStatusShortName=SocialNGO

############################################################################################################
#Occupation
occupationName=Stock Broker
occupationShortName=MF Advisor
		
############################################################################################################

############################################################################################################
				
############################################################################################################




























































