#Home/Process/Confirmation/RM Recommendation
#ConfirmRMRecKyphEmailTC
rmRecOrgName= Sathya IFA-1
rmRecTemplateDD= T48A_Recommendation.html
rmRecText=Hi from Mail text
rmRecSubject=Hi from Mail subject
rmRecWhenToSendDate=23/02/2021
rmRecWTShoursDD=17
rmRecWTSminutesDD=10
rmRecDocNo=23
rmRecSendToKYPHcodes=UCIC153550


#Home/Process/Broker/Fetch Broker Ledger Txn
#BrokerFetchBroLedTxnTC
LedTxnstartDate=12/02/2021
LedTxnendDate=23/02/2021


#Home/Process/File Process And Dashboard/Run File Process
#FileProcessRunFileProcessTC
RunFileModuleDD= Pledge-Physical


#Home/Process/Indices/Benchmark / Indices/Benchmark Values
#IndicesBenchCreateIndiceValTC
ibIndicesCodeDD=BANKNIFTY
ibIndicesName=SBI BANK NIFTY
ibPrice=500
ibDate=25/02/2021


#Home /Process/Upload Process/Revalidate
#UploadProcRevalidateTC
revalidateSelectModule= PMR Revalidate


#Home/Process/EOD and Dashboard/Run Eod Process
#RunEodProEQDMATC
runEodDate=25/02/2021




