#Reports

#bulk SMS
bsOrgNameDD= Sathya IFA-1
bsTemplateDD= T22
bsMobileNo=9902602233


#Send email
keOrgNameDD= Sathya IFA-1
keTemplateDD= T140A_Kyph_WelcomeLetter.html
keKyphUcic=UCIC153550

#DSR
dsrClientName=Ram Chennale
dsrContactDetails=80662454321
dsrTypeOfContactDD=Phone Call
dsrDateOfContact=17/02/2021
dsrHourOfContactDD=20
dsrMinuteOfContactDD=20
dsrPersonContacted=Ramesh
dsrCallSummary=05:32

#Push Notification
OrgName= Sathya IFA-1
pnSendTo=Selected Kyphs
pnkyphId=152697
pnremarks=send notification

#Reports/Large Report Execute
#Updating  Portfolio Holding
holdingPortfolio=all txn
portfolio=IA149389_QQAMA7845P_all txn_all txn_IA149389E149385_all txn
holdingDate=18/02/2021

#
ledgerPortfolio=all txn
ledgerStartDate=10/02/2021
ledgerEndDate=17/02/2021

#corp Portfolio
corpPortfolio=all txn
selectCorpPortfolio=IA149389_QQAMA7845P_all txn_all txn_IA149389E149385_all txn
corpDate=17/02/2021

#RM Report
searchPortfolio=all txn
