#################################################
#
feePosting=1st Day of next period
effectiveDate=12/02/2021

##################################################
#
fpfFeesTypeDD=Transaction
fpffamilyAutoSugg=all txn
selectfpffamilyAutoSugg=all txn's Family (UCIC153550)-FRN_148323
fpfStartDate=11/02/2021
fpfEndDate=24/02/2021
fpfFrequencyDD=Monthly

##################################################
#Home/RIMS/Client Fees/7a. Integ.Fees-Create Rule=  CreateIntFeesCreateRuleTC
creatRulePortfolioCodeAutoSugg=all txn
selectcreatRulePortfolioCodeAutoSugg=IA149389E149385_QQAMA7845P_all txn_all txn
creatRuleEffectiveDate=20/02/2021
creatRuleFee_methodDD=Daily Average NAV
creatRuleIntegratedDD=No
creatRulefrequencyDD=Monthly
creatRuleEquityFees=1
creatRuleDebtFees=2
creatRuleAlternative=3
creatRuleRealState=4
creatRuleCashEquivalent=5
creatRuleFeesAmountPA=1000


##################################################
#Home/RIMS/Client Fees/7b. Integrated Fees-Calculate = CreateIntegFeesCalculateTC
feesCalselectFeesTypeDD=NAV
feesCalstartDate=10/02/2021
feesCalendDate=20/02/2021
feesCalEtrPortfolioCode=IA149389E149385

#Home/RIMS/Client Fees/7c. Integ.Fees-Post Fees = CreateIntegFeesPostFeesTC
postFeesFeesTypeDD=Transaction
postFeesChooseDate=20/02/2021

#Home/RIMS/Client Fees/8. Performance Fees  =CreatePerfoFeesTC
pfPortfolioCode=IA149389E149385
pfEffectiveDate=19/02/2021
pfMethodDD=TWRR
pfRate=10

#Home/RIMS/MF Revenue/MF Fees Calculation= 
#MFFeesCalTC
mfTrailSdate=19/02/2021
mfTrailEdate=22/02/2021

#Home/RIMS/MF Revenue/MF Fees Exception Calculation
#MFTrailFeesExcepCalTC
mfTrailExcepSdate=19/02/2021
mfTrailExcepEdate=22/02/2021

#Home/RIMS/MF Revenue/5. AMC Commission Receipt
#CreateAMCCommiReceiptTC
amcCmRAMCnameDD=
amcCmRstateDD=KARNATAKA
amcCmRtypeDD=Domestic
amcCmRReceiptDate=22/02/2021
amcCmRcbsDate=22/02/2021
amcCmRcbsRefNo=2323

#Home/RIMS/MF Revenue/Rev Type Master
#CreateRevTypeMasterTC
RevTypeMasName=Upfront


#Home/RIMS/MF Revenue/RTA Rev Type Mapping
#CreateRTARevTypeMappingTC
rtaRevMappingRtaNameDD=Cams
rtaRevMappingRtaRevCode=Cams23
rtaRevMappingCaliMfRevTypeId=Additional Brokerage


#Home/RIMS/MF Revenue/RTA Revenue Files
#RTARevenueFileProcessTC
rtaRevFRIMSRtaTypeDD=RIMS Cams WBR77 DBF
rtaRevFOrg= Sathya IFA-1

#Home/RIMS/RIMS Update/Family-wise Split Master
#CreateFamilyWiseSplitMasterTC
fSplitFamilynameAutoSugg=all txn
selectfSplitFamilynameAutoSugg=all txn's Family (UCIC153550)_FRN_148323
fSplitRmTypeDD=Primary
fSplitSharePercent=20
fSplitShareType=Real
fSplitEffectiveFrom=01/02/2021
fSplitEffectiveTo=23/02/2021


#Home/RIMS/RIMS Update/RIMS Rerun
#RIMSRerunUpFamilyRMMappingTC
familyRmMappingSdate=01/02/2021
familyRmMappingEdate=23/02/2021

#Home/RIMS/Rims Update/RIMS B
#RimsBSplitRevenueTC
RimsBFamilyId=147480
RimsBstartDate=01/02/2021
RimsBendDate=23/02/2021
